### ISSUE TITLE
Add return to the solve() function

### ISSUE THREAD

**Issue by AlejandroMonteseirin** [tcbegley/cube-solver#1]
actually the solve function only prints the results, I workaround this problem by adding 
             

> self.solution=self._solution_to_string(n)

       
to the line before 141 in solve.py to return the last solution

**Comment by tcbegley** [comment]
Good suggestion. I've only ever really used this interactively, but having a return value so this can be extended more easily seems like a sensible idea.

**Comment by tcbegley** [comment]
Hey @AlejandroMonteseirin 

Sorry it's been over a year, possibly you don't care any more, but I finally found time to make some improvements, in particular returning the value rather than printing it like you suggested.

You can now do this

```python
from twophase import solve

solve("<cube_string>")  # returns the solution
```

Will close this now.
